/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppCidadesRouteImport } from './routes/_app.cidades'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppEmpresasRouteImport } from './routes/_app.empresas'
import { Route as AppFuncionariosRouteImport } from './routes/_app.funcionarios'
import { Route as AppPedidosRouteImport } from './routes/_app.pedidos'
import { Route as AppServicosRouteImport } from './routes/_app.servicos'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCidadesRoute = AppCidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppFuncionariosRoute = AppFuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cidades': typeof AppCidadesRoute
  '/clientes': typeof AppClientesRoute
  '/empresas': typeof AppEmpresasRoute
  '/funcionarios': typeof AppFuncionariosRoute
  '/pedidos': typeof AppPedidosRoute
  '/servicos': typeof AppServicosRoute
}
export interface FileRoutesByTo {
  '/cidades': typeof AppCidadesRoute
  '/clientes': typeof AppClientesRoute
  '/empresas': typeof AppEmpresasRoute
  '/funcionarios': typeof AppFuncionariosRoute
  '/pedidos': typeof AppPedidosRoute
  '/servicos': typeof AppServicosRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/cidades': typeof AppCidadesRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/empresas': typeof AppEmpresasRoute
  '/_app/funcionarios': typeof AppFuncionariosRoute
  '/_app/pedidos': typeof AppPedidosRoute
  '/_app/servicos': typeof AppServicosRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cidades'
    | '/clientes'
    | '/empresas'
    | '/funcionarios'
    | '/pedidos'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cidades'
    | '/clientes'
    | '/empresas'
    | '/funcionarios'
    | '/pedidos'
    | '/servicos'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/cidades'
    | '/_app/clientes'
    | '/_app/empresas'
    | '/_app/funcionarios'
    | '/_app/pedidos'
    | '/_app/servicos'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cidades': {
      id: '/_app/cidades'
      path: '/cidades'
      fullPath: '/cidades'
      preLoaderRoute: typeof AppCidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresas': {
      id: '/_app/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funcionarios': {
      id: '/_app/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AppFuncionariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos': {
      id: '/_app/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servicos': {
      id: '/_app/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCidadesRoute: typeof AppCidadesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppFuncionariosRoute: typeof AppFuncionariosRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppServicosRoute: typeof AppServicosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCidadesRoute: AppCidadesRoute,
  AppClientesRoute: AppClientesRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppFuncionariosRoute: AppFuncionariosRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppServicosRoute: AppServicosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
